export const ADD_NEW_PRODUCTS = "ADD_NEW_PRODUCTS";
export const ADD_SALE_PRODUCTS = "ADD_SALE_PRODUCTS";
export const ADD_HOME_BANNER = "ADD_HOME_BANNER";

export const ADD_FAVORITE_CATEGORIES = "ADD_FAVORITE_CATEGORIES";
export const ADD_FAVORITE_PRODUCTS = "ADD_FAVORITE_PRODUCTS";

export const ADD_BAG_PRODUCTS = "ADD_BAG_PRODUCTS";